### ISSUE TITLE
Don't override color styling from stylus extension

### ISSUE THREAD

**Issue by tgreen7** [NickyMateev/Line-Clipper#3]
I am using the chrome extension stylus to change my github to dark theme:

<img width="222" alt="Screen Shot 2020-04-30 at 6 32 31 PM" src="https://user-images.githubusercontent.com/10415101/80774127-f850bd80-8b10-11ea-9e27-50d3378c57b9.png">

and with this extension active the line numbers disappear:

<img width="209" alt="Screen Shot 2020-04-30 at 6 32 52 PM" src="https://user-images.githubusercontent.com/10415101/80774162-0d2d5100-8b11-11ea-90d1-29d6b522f7fa.png">

Not sure how much work it would be to get this working with custom styles.

This is the stylus theme i am using: https://github.com/StylishThemes/GitHub-Dark

**Comment by NickyMateev** [comment]
Hi @tgreen7,

Thanks for opening this issue - I didn't take into account that there are numerous theme plugins which might change the color of GitHub elements and so I had "hard-coded" a specific color, which in your case made the lines disappear, unfortunately.

I have fixed this with this latest commit: https://github.com/NickyMateev/Line-Clipper/commit/731e9bada2ef60598699cada9885c8a66d6c0109

I'll make a new release at the end of this week (May 3rd), so that I can cover any other possible bugs if something comes up until then. Keep in mind that the Chrome Web Store takes a couple of days after a new release has been published - so if you are eager to test it out or start using this plugin, you can follow the local machine installation guide here: https://github.com/NickyMateev/Line-Clipper#installation

Cheers! 😄🍻

P.S. I have started using this GitHub Stylus plugin myself now that you mentioned it - I really like it!

**Comment by NickyMateev** [comment]
Fix provided with release 1.0.2: https://github.com/NickyMateev/Line-Clipper/releases/tag/v1.0.2

Mozilla Add-ons already has the new version.
It will take 1-2 business days to have it reviewed on Chrome Web Store.
